site_name: "dot-connect"
repo_url: https://github.com/learning-the-computers/dot-connect
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  icon:
  logo: static/icons/dot-connect.png
  favicon: static/icons/dot-connect.png
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - Backends:
    - AWS: backends/aws.md
    - Azure: backends/azure.md
    - Impala: backends/impala.md
    - Microsoft SQL Server: backends/mssql.md
    - MySQL: backends/mysql.md
    - PostgreSQL: backends/postgres.md
    - PySpark: backends/pyspark.md
    - Snowflake: backends/snowflake.md
    - Snowpark: backends/snowpark.md
  - Examples:
    - Snowflake: examples/snowflake.md
    - Snowpark: examples/snowpark.md
  - About: about.md
